databases:
  - name: django_ecommerce_db
    region: singapore
    plan: free
    databaseName: django_ecommerce_db
    user: user

services:
  - type: web
    name: django_ecommerce
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn backend.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: django_ecommerce_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true